// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.1
// source: scheme.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "controls";

export interface ControlScheme {
  version: string;
  /** "portrait" or "landscape" */
  orientation: string;
  touchEnabled?: boolean | undefined;
  accelerometerEnabled?: boolean | undefined;
  width?: number | undefined;
  height?: number | undefined;
  resources: AppResource[];
  displayObjects: DisplayObject[];
  options: ContextMenuOption[];
}

export interface AppResource {
  id: number;
  bitmap: Uint8Array;
}

export interface DisplayObject {
  id: number;
  type: string;
  top: number;
  left: number;
  width: number;
  height: number;
  functionHandler: string;
  hidden: boolean;
  hasHitRect: boolean;
  hitTop?: number | undefined;
  hitLeft?: number | undefined;
  hitWidth?: number | undefined;
  hitHeight?: number | undefined;
  text: string;
  textSize?: number | undefined;
  color?:
    | number
    | undefined;
  /** "linear" or "nearest" */
  samplingMode: string;
  deadzone?: number | undefined;
  radial?: boolean | undefined;
  assets: ControlAsset[];
}

export interface ControlAsset {
  name: string;
  resourceRef: number;
}

export interface ContextMenuOption {
  iconResId: number;
  title: string;
  event: string;
  closeOnSelect: boolean;
}

function createBaseControlScheme(): ControlScheme {
  return {
    version: "",
    orientation: "",
    touchEnabled: undefined,
    accelerometerEnabled: undefined,
    width: undefined,
    height: undefined,
    resources: [],
    displayObjects: [],
    options: [],
  };
}

export const ControlScheme: MessageFns<ControlScheme> = {
  encode(message: ControlScheme, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== "") {
      writer.uint32(10).string(message.version);
    }
    if (message.orientation !== "") {
      writer.uint32(18).string(message.orientation);
    }
    if (message.touchEnabled !== undefined) {
      writer.uint32(24).bool(message.touchEnabled);
    }
    if (message.accelerometerEnabled !== undefined) {
      writer.uint32(32).bool(message.accelerometerEnabled);
    }
    if (message.width !== undefined) {
      writer.uint32(40).int32(message.width);
    }
    if (message.height !== undefined) {
      writer.uint32(48).int32(message.height);
    }
    for (const v of message.resources) {
      AppResource.encode(v!, writer.uint32(58).fork()).join();
    }
    for (const v of message.displayObjects) {
      DisplayObject.encode(v!, writer.uint32(66).fork()).join();
    }
    for (const v of message.options) {
      ContextMenuOption.encode(v!, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ControlScheme {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseControlScheme();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orientation = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.touchEnabled = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.accelerometerEnabled = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.width = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.height = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.resources.push(AppResource.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.displayObjects.push(DisplayObject.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.options.push(ContextMenuOption.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ControlScheme {
    return {
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      orientation: isSet(object.orientation) ? globalThis.String(object.orientation) : "",
      touchEnabled: isSet(object.touchEnabled)
        ? globalThis.Boolean(object.touchEnabled)
        : isSet(object.touch_enabled)
        ? globalThis.Boolean(object.touch_enabled)
        : undefined,
      accelerometerEnabled: isSet(object.accelerometerEnabled)
        ? globalThis.Boolean(object.accelerometerEnabled)
        : isSet(object.accelerometer_enabled)
        ? globalThis.Boolean(object.accelerometer_enabled)
        : undefined,
      width: isSet(object.width) ? globalThis.Number(object.width) : undefined,
      height: isSet(object.height) ? globalThis.Number(object.height) : undefined,
      resources: globalThis.Array.isArray(object?.resources)
        ? object.resources.map((e: any) => AppResource.fromJSON(e))
        : [],
      displayObjects: globalThis.Array.isArray(object?.displayObjects)
        ? object.displayObjects.map((e: any) => DisplayObject.fromJSON(e))
        : globalThis.Array.isArray(object?.display_objects)
        ? object.display_objects.map((e: any) => DisplayObject.fromJSON(e))
        : [],
      options: globalThis.Array.isArray(object?.options)
        ? object.options.map((e: any) => ContextMenuOption.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ControlScheme): unknown {
    const obj: any = {};
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.orientation !== "") {
      obj.orientation = message.orientation;
    }
    if (message.touchEnabled !== undefined) {
      obj.touchEnabled = message.touchEnabled;
    }
    if (message.accelerometerEnabled !== undefined) {
      obj.accelerometerEnabled = message.accelerometerEnabled;
    }
    if (message.width !== undefined) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== undefined) {
      obj.height = Math.round(message.height);
    }
    if (message.resources?.length) {
      obj.resources = message.resources.map((e) => AppResource.toJSON(e));
    }
    if (message.displayObjects?.length) {
      obj.displayObjects = message.displayObjects.map((e) => DisplayObject.toJSON(e));
    }
    if (message.options?.length) {
      obj.options = message.options.map((e) => ContextMenuOption.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ControlScheme>, I>>(base?: I): ControlScheme {
    return ControlScheme.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ControlScheme>, I>>(object: I): ControlScheme {
    const message = createBaseControlScheme();
    message.version = object.version ?? "";
    message.orientation = object.orientation ?? "";
    message.touchEnabled = object.touchEnabled ?? undefined;
    message.accelerometerEnabled = object.accelerometerEnabled ?? undefined;
    message.width = object.width ?? undefined;
    message.height = object.height ?? undefined;
    message.resources = object.resources?.map((e) => AppResource.fromPartial(e)) || [];
    message.displayObjects = object.displayObjects?.map((e) => DisplayObject.fromPartial(e)) || [];
    message.options = object.options?.map((e) => ContextMenuOption.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAppResource(): AppResource {
  return { id: 0, bitmap: new Uint8Array(0) };
}

export const AppResource: MessageFns<AppResource> = {
  encode(message: AppResource, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.bitmap.length !== 0) {
      writer.uint32(18).bytes(message.bitmap);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppResource {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppResource();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bitmap = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AppResource {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      bitmap: isSet(object.bitmap) ? bytesFromBase64(object.bitmap) : new Uint8Array(0),
    };
  },

  toJSON(message: AppResource): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.bitmap.length !== 0) {
      obj.bitmap = base64FromBytes(message.bitmap);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AppResource>, I>>(base?: I): AppResource {
    return AppResource.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AppResource>, I>>(object: I): AppResource {
    const message = createBaseAppResource();
    message.id = object.id ?? 0;
    message.bitmap = object.bitmap ?? new Uint8Array(0);
    return message;
  },
};

function createBaseDisplayObject(): DisplayObject {
  return {
    id: 0,
    type: "",
    top: 0,
    left: 0,
    width: 0,
    height: 0,
    functionHandler: "",
    hidden: false,
    hasHitRect: false,
    hitTop: undefined,
    hitLeft: undefined,
    hitWidth: undefined,
    hitHeight: undefined,
    text: "",
    textSize: undefined,
    color: undefined,
    samplingMode: "",
    deadzone: undefined,
    radial: undefined,
    assets: [],
  };
}

export const DisplayObject: MessageFns<DisplayObject> = {
  encode(message: DisplayObject, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.top !== 0) {
      writer.uint32(29).float(message.top);
    }
    if (message.left !== 0) {
      writer.uint32(37).float(message.left);
    }
    if (message.width !== 0) {
      writer.uint32(45).float(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(53).float(message.height);
    }
    if (message.functionHandler !== "") {
      writer.uint32(58).string(message.functionHandler);
    }
    if (message.hidden !== false) {
      writer.uint32(64).bool(message.hidden);
    }
    if (message.hasHitRect !== false) {
      writer.uint32(72).bool(message.hasHitRect);
    }
    if (message.hitTop !== undefined) {
      writer.uint32(85).float(message.hitTop);
    }
    if (message.hitLeft !== undefined) {
      writer.uint32(93).float(message.hitLeft);
    }
    if (message.hitWidth !== undefined) {
      writer.uint32(101).float(message.hitWidth);
    }
    if (message.hitHeight !== undefined) {
      writer.uint32(109).float(message.hitHeight);
    }
    if (message.text !== "") {
      writer.uint32(114).string(message.text);
    }
    if (message.textSize !== undefined) {
      writer.uint32(125).float(message.textSize);
    }
    if (message.color !== undefined) {
      writer.uint32(128).int32(message.color);
    }
    if (message.samplingMode !== "") {
      writer.uint32(138).string(message.samplingMode);
    }
    if (message.deadzone !== undefined) {
      writer.uint32(149).float(message.deadzone);
    }
    if (message.radial !== undefined) {
      writer.uint32(152).bool(message.radial);
    }
    for (const v of message.assets) {
      ControlAsset.encode(v!, writer.uint32(162).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisplayObject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisplayObject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.top = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.left = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.width = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.height = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.functionHandler = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.hidden = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.hasHitRect = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 85) {
            break;
          }

          message.hitTop = reader.float();
          continue;
        }
        case 11: {
          if (tag !== 93) {
            break;
          }

          message.hitLeft = reader.float();
          continue;
        }
        case 12: {
          if (tag !== 101) {
            break;
          }

          message.hitWidth = reader.float();
          continue;
        }
        case 13: {
          if (tag !== 109) {
            break;
          }

          message.hitHeight = reader.float();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 125) {
            break;
          }

          message.textSize = reader.float();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.color = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.samplingMode = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 149) {
            break;
          }

          message.deadzone = reader.float();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.radial = reader.bool();
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.assets.push(ControlAsset.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DisplayObject {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      top: isSet(object.top) ? globalThis.Number(object.top) : 0,
      left: isSet(object.left) ? globalThis.Number(object.left) : 0,
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      functionHandler: isSet(object.functionHandler)
        ? globalThis.String(object.functionHandler)
        : isSet(object.function_handler)
        ? globalThis.String(object.function_handler)
        : "",
      hidden: isSet(object.hidden) ? globalThis.Boolean(object.hidden) : false,
      hasHitRect: isSet(object.hasHitRect)
        ? globalThis.Boolean(object.hasHitRect)
        : isSet(object.has_hit_rect)
        ? globalThis.Boolean(object.has_hit_rect)
        : false,
      hitTop: isSet(object.hitTop)
        ? globalThis.Number(object.hitTop)
        : isSet(object.hit_top)
        ? globalThis.Number(object.hit_top)
        : undefined,
      hitLeft: isSet(object.hitLeft)
        ? globalThis.Number(object.hitLeft)
        : isSet(object.hit_left)
        ? globalThis.Number(object.hit_left)
        : undefined,
      hitWidth: isSet(object.hitWidth)
        ? globalThis.Number(object.hitWidth)
        : isSet(object.hit_width)
        ? globalThis.Number(object.hit_width)
        : undefined,
      hitHeight: isSet(object.hitHeight)
        ? globalThis.Number(object.hitHeight)
        : isSet(object.hit_height)
        ? globalThis.Number(object.hit_height)
        : undefined,
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      textSize: isSet(object.textSize)
        ? globalThis.Number(object.textSize)
        : isSet(object.text_size)
        ? globalThis.Number(object.text_size)
        : undefined,
      color: isSet(object.color) ? globalThis.Number(object.color) : undefined,
      samplingMode: isSet(object.samplingMode)
        ? globalThis.String(object.samplingMode)
        : isSet(object.sampling_mode)
        ? globalThis.String(object.sampling_mode)
        : "",
      deadzone: isSet(object.deadzone) ? globalThis.Number(object.deadzone) : undefined,
      radial: isSet(object.radial) ? globalThis.Boolean(object.radial) : undefined,
      assets: globalThis.Array.isArray(object?.assets)
        ? object.assets.map((e: any) => ControlAsset.fromJSON(e))
        : [],
    };
  },

  toJSON(message: DisplayObject): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.top !== 0) {
      obj.top = message.top;
    }
    if (message.left !== 0) {
      obj.left = message.left;
    }
    if (message.width !== 0) {
      obj.width = message.width;
    }
    if (message.height !== 0) {
      obj.height = message.height;
    }
    if (message.functionHandler !== "") {
      obj.functionHandler = message.functionHandler;
    }
    if (message.hidden !== false) {
      obj.hidden = message.hidden;
    }
    if (message.hasHitRect !== false) {
      obj.hasHitRect = message.hasHitRect;
    }
    if (message.hitTop !== undefined) {
      obj.hitTop = message.hitTop;
    }
    if (message.hitLeft !== undefined) {
      obj.hitLeft = message.hitLeft;
    }
    if (message.hitWidth !== undefined) {
      obj.hitWidth = message.hitWidth;
    }
    if (message.hitHeight !== undefined) {
      obj.hitHeight = message.hitHeight;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.textSize !== undefined) {
      obj.textSize = message.textSize;
    }
    if (message.color !== undefined) {
      obj.color = Math.round(message.color);
    }
    if (message.samplingMode !== "") {
      obj.samplingMode = message.samplingMode;
    }
    if (message.deadzone !== undefined) {
      obj.deadzone = message.deadzone;
    }
    if (message.radial !== undefined) {
      obj.radial = message.radial;
    }
    if (message.assets?.length) {
      obj.assets = message.assets.map((e) => ControlAsset.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DisplayObject>, I>>(base?: I): DisplayObject {
    return DisplayObject.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DisplayObject>, I>>(object: I): DisplayObject {
    const message = createBaseDisplayObject();
    message.id = object.id ?? 0;
    message.type = object.type ?? "";
    message.top = object.top ?? 0;
    message.left = object.left ?? 0;
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    message.functionHandler = object.functionHandler ?? "";
    message.hidden = object.hidden ?? false;
    message.hasHitRect = object.hasHitRect ?? false;
    message.hitTop = object.hitTop ?? undefined;
    message.hitLeft = object.hitLeft ?? undefined;
    message.hitWidth = object.hitWidth ?? undefined;
    message.hitHeight = object.hitHeight ?? undefined;
    message.text = object.text ?? "";
    message.textSize = object.textSize ?? undefined;
    message.color = object.color ?? undefined;
    message.samplingMode = object.samplingMode ?? "";
    message.deadzone = object.deadzone ?? undefined;
    message.radial = object.radial ?? undefined;
    message.assets = object.assets?.map((e) => ControlAsset.fromPartial(e)) || [];
    return message;
  },
};

function createBaseControlAsset(): ControlAsset {
  return { name: "", resourceRef: 0 };
}

export const ControlAsset: MessageFns<ControlAsset> = {
  encode(message: ControlAsset, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.resourceRef !== 0) {
      writer.uint32(16).int32(message.resourceRef);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ControlAsset {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseControlAsset();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.resourceRef = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ControlAsset {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      resourceRef: isSet(object.resourceRef)
        ? globalThis.Number(object.resourceRef)
        : isSet(object.resource_ref)
        ? globalThis.Number(object.resource_ref)
        : 0,
    };
  },

  toJSON(message: ControlAsset): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.resourceRef !== 0) {
      obj.resourceRef = Math.round(message.resourceRef);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ControlAsset>, I>>(base?: I): ControlAsset {
    return ControlAsset.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ControlAsset>, I>>(object: I): ControlAsset {
    const message = createBaseControlAsset();
    message.name = object.name ?? "";
    message.resourceRef = object.resourceRef ?? 0;
    return message;
  },
};

function createBaseContextMenuOption(): ContextMenuOption {
  return { iconResId: 0, title: "", event: "", closeOnSelect: false };
}

export const ContextMenuOption: MessageFns<ContextMenuOption> = {
  encode(message: ContextMenuOption, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.iconResId !== 0) {
      writer.uint32(8).int32(message.iconResId);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.event !== "") {
      writer.uint32(26).string(message.event);
    }
    if (message.closeOnSelect !== false) {
      writer.uint32(32).bool(message.closeOnSelect);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ContextMenuOption {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseContextMenuOption();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.iconResId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.event = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.closeOnSelect = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ContextMenuOption {
    return {
      iconResId: isSet(object.iconResId)
        ? globalThis.Number(object.iconResId)
        : isSet(object.icon_res_id)
        ? globalThis.Number(object.icon_res_id)
        : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      event: isSet(object.event) ? globalThis.String(object.event) : "",
      closeOnSelect: isSet(object.closeOnSelect)
        ? globalThis.Boolean(object.closeOnSelect)
        : isSet(object.close_on_select)
        ? globalThis.Boolean(object.close_on_select)
        : false,
    };
  },

  toJSON(message: ContextMenuOption): unknown {
    const obj: any = {};
    if (message.iconResId !== 0) {
      obj.iconResId = Math.round(message.iconResId);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.event !== "") {
      obj.event = message.event;
    }
    if (message.closeOnSelect !== false) {
      obj.closeOnSelect = message.closeOnSelect;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ContextMenuOption>, I>>(base?: I): ContextMenuOption {
    return ContextMenuOption.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ContextMenuOption>, I>>(object: I): ContextMenuOption {
    const message = createBaseContextMenuOption();
    message.iconResId = object.iconResId ?? 0;
    message.title = object.title ?? "";
    message.event = object.event ?? "";
    message.closeOnSelect = object.closeOnSelect ?? false;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
